### ISSUE TITLE
BayesianGPLVM mean_function missing

### ISSUE THREAD

**Issue by lionfish0** [SheffieldML/GPy#244] opened 2015-09-11 17:07 UTC
/home/lionfish/anaconda/lib/python2.7/site-packages/GPy-0.8.8-py2.7-linux-x86_64.egg/GPy/core/gp.pyc in _raw_predict(self, Xnew, full_cov, kern)
    238             var = var
    239         #add in the mean function
--> 240         if self.mean_function is not None:
    241             mu += self.mean_function.f(Xnew)
    242 

AttributeError: 'BayesianGPLVM' object has no attribute 'mean_function'

was able to reproduce error using the GPSS_Lab1_gplvm notebook, and the line:
lvm_visualizer = GPy.plotting.matplot_dep.visualize.lvm_dimselect(m.X.mean.copy(), m, data_show, ax_latent, ax_scales, labels=labels.flatten())

**Comment by mzwiessele** [comment] 2015-09-11 17:53
Is this on the current Master branch?

**Comment by mzwiessele** [comment] 2015-10-13 06:34
I cannot reproduce this error. and no answers, closing.

**Closed by mzwiessele** 2015-10-13 06:34 UTC
Labels: bug
