### ISSUE TITLE
GPy should check if kernel input_dim and dimension of X match

### ISSUE THREAD

**Issue by nnmm** [SheffieldML/GPy#198] opened 2015-05-21 15:06 UTC
This would prevent errors when users write simple 1D examples and extend them to more dimensions. If the input_dim is not changed, GPy doesn't warn the user. Instead, predict() returns 1D results (and looking into the source of the error may involve stepping through the complicated slicing mechanism).

**Comment by jameshensman** [comment] 2015-05-22 14:30
I agree, this would be a good feature.

**Comment by alansaul** [comment] 2015-07-22 17:56
Just to check, do you mean to do this on any call to the kernel? The reason I ask is that I find it quite a useful feature being able to choose some active_dims that don't cover the full range of X.shape[1], so I can chop and change them easily. I may be misunderstanding the request though!

**Comment by mzwiessele** [comment] 2015-09-09 18:17
I do not agree. But, what I can do is do **1** warning, at creation time of the GP object, although this is creating all sorts of dependencies and knowledge of the model about the kernel and could be hindering further development of kernels. 

The behaviour of kernels handling more dimensional inputs (X), as they have is very expected. Maybe a warning in the docs should suffice?

**Comment by mzwiessele** [comment] 2015-10-01 17:13
I had a play and it is not good to do this. I see what the problem is, but in general the dimensions do not have to match up. I still have to fix the active dims, though, which should actually reflect the actually used dimensions of X! This can then be used to warn the user at creation time of the model.

**Comment by mzwiessele** [comment] 2015-10-13 07:30
fixed by 5b57f75

**Closed by mzwiessele** 2015-10-13 07:30 UTC
Labels: enhancement, wontfix
