### ISSUE TITLE
Kernel changes after predicting

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#334] opened 2016-03-15 12:52 UTC
I'm not sure if this is a bug, but at least I don't understand why this happens and it seems really weird. If I predict for a kernel that is a sum of (some of) the model's kernels, the model's kernel actually changes for some reason. Consider this example:

``` python
kern1 = GPy.kern.RBF(input_dim=1, name='kern1')
kern2 = GPy.kern.RBF(input_dim=1, name='kern2')
kern3 = GPy.kern.RBF(input_dim=1, name='kern3')
x = np.random.randn(100, 1)
y = np.random.randn(100, 1)
m = GPy.models.GPRegression(x, y, kernel=kern1+kern2+kern3)
# No problem
m.predict(x, kern=kern1+kern2)
display(m)
# No problem
m.predict(x, kern=m.kern.kern1)
display(m)
# Problem (sum of kernels accessed via the model object)
m.predict(x, kern=m.kern.kern1+m.kern.kern2)
display(m)
```

The last display command shows that the model has dropped kernels kern1 and kern2. Why? How should I predict using a kernel that is a sum of some of the kernels?

It also seems that using `kern1`, `kern2`, `kern3`, instead of `m.kern.kern1`, `m.kern.kern2`, `m.kern.kern3` is not the correct way, because after an optimization `kern1` et al don't have the optimized parameter values. That is also slightly confusing (a bug?) but I thought the solution was to access the kernels via the model object. But now I'm a bit lost.

Any ideas? Am I just doing something wrong here?

**Comment by mzwiessele** [comment] 2016-03-15 14:01
Omg, yes that is a bug! 

Thanks for spotting it, I will have a look.

I think we will just have to make the reusability a little less. The current way was, that kernels, which went into the sum, were not copied, but we will have to copy them.

You are using it exactly how it was intended to be used, but we oversay this issue.

Thanks!

**Comment by mzwiessele** [comment] 2016-03-15 14:04
For now, you can resolve this by making copies of the kernels of the model for the prediction:

```
m.predict(Xpred, kern=m.kern.kern1.copy()+m.kern.kern3.copy())
```

and it will not touch the kernels of the model.

**Comment by jluttine** [comment] 2016-03-15 14:39
Thanks a lot for the workaround! :+1:

**Comment by mzwiessele** [comment] 2016-08-16 10:42
fixed by https://github.com/SheffieldML/GPy/commit/7135527fd00f0a385b65bfb32f9535c3859d1f8a

**Closed as completed by mzwiessele** 2016-08-16 10:42 UTC
Labels: bug
