### ISSUE TITLE
Running GPy in a cluster

### ISSUE THREAD

**Issue by thanpan** [SheffieldML/GPy#251] opened 2015-09-14 15:38 UTC
There seems to be a conflict when running a simple GP regression from GPy in an MPI environment:

An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

Is there a fork() call in GPy when running a simple GP regression?
Thank you.

**Comment by zhenwendai** [comment] 2015-09-23 15:29
There is no fork() call in GPy. I think it might be an compatibility issue between mpi4py and the underlying MPI environment in your cluster environment.

I cannot reproduce your error, but I removed the automatic importing of mpi4py. The fix is in the devel branch. Hope it solves your problem.

**Comment by mzwiessele** [comment] 2015-11-20 15:07
is this fixed, can we close?

**Comment by apanagopoulos** [comment] 2015-11-20 15:21
I think it was a compatibility issue with a threadpool component I was using. Managed to run GPY in the cluster without this component. Thank you

**Closed** 2016-03-06 10:28 UTC
