### ISSUE TITLE
Maximum Recursion Depth exceeded when adding kernels

### ISSUE THREAD

**Issue by ssydasheng** [SheffieldML/GPy#591] opened 2018-01-10 14:39 UTC
```
import GPy
kerns = [GPy.kern.RBF(6) for _ in range(10)]
sum = GPy.kern.Add(kerns)
GPy.kern.Add([sum, sum, sum])
```
This four-line code will give errors like
```
File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 454, in warn_and_retry
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 336, in __setattr__
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/nameable.py", line 74, in name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 481, in _name_changed
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 478, in _remove_parameter_name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 273, in _connect_parameters
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 459, in _add_parameter_name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 454, in warn_and_retry
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 336, in __setattr__
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/nameable.py", line 74, in name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 481, in _name_changed
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 478, in _remove_parameter_name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 273, in _connect_parameters
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 459, in _add_parameter_name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 454, in warn_and_retry
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 336, in __setattr__
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/nameable.py", line 74, in name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 481, in _name_changed
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 478, in _remove_parameter_name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 273, in _connect_parameters
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 459, in _add_parameter_name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 454, in warn_and_retry
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 336, in __setattr__
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/nameable.py", line 72, in name
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/parameterized.py", line 332, in __setattr__
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 185, in parameter_names
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/parameter_core.py", line 185, in <listcomp>
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/site-packages/paramz-0.8.5-py3.6.egg/paramz/core/nameable.py", line 44, in adjust_name_for_printing
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
  File "/u/ssy/anaconda3/envs/cp3/lib/python3.6/re.py", line 289, in _compile
    p, loc = _cache[type(pattern), pattern, flags]
RecursionError: maximum recursion depth exceeded while calling a Python object
```
What's more, it seems way slower to add `GPy.kern.Add` object compared to add standard kernels.

**Comment by zhenwendai** [comment] 2018-01-11 18:20
@mzwiessele, Could you have a look at this issue? It seems the problem is located in paramz.

**Comment by mzwiessele** [comment] 2018-01-12 09:30
Sure, on it.

**Comment by mzwiessele** [comment] 2018-01-16 11:15
It has to do with the recursion limit. We set the names of the parameters recursively to not overlap. This is being done by comparing pairwise, which slows down the code significantly. Two solutions come to mind:

 - Either you set the names of the individual parts directly (**FAST**):
```python
sum = GPy.kern.Add([GPy.kern.RBF(6, ARD=True, name="RBF_{}".format(i)) for i in range(40)])
```
 - or you increase the recursionlimit, so that the program does it for you (**SLOW**):
```python
sys.setrecursionlimit(10000)
sum = GPy.kern.Add([GPy.kern.RBF(6, ARD=True) for i in range(40)])
```

**Comment by mzwiessele** [comment] 2018-01-16 12:03
fixed in https://github.com/sods/paramz/commit/b5cd7993ca235bb545844dde1c2db4641aea4295

**Closed as completed by mzwiessele** 2018-01-16 12:03 UTC
