### ISSUE TITLE
pypi package is broken

### ISSUE THREAD

**Issue by zxytim** [SheffieldML/GPy#190] opened 2015-04-19 17:06 UTC
https://pypi.python.org/packages/source/G/GPy/GPy-0.6.0.tar.gz#md5=7c3314c9cf4d46610732046bbb995d49

you can find following incorrectly pushed files which will cause SyntaxError while installing using pip:
./GPy/likelihoods/link_functions.py.BASE.29640.py
./GPy/likelihoods/link_functions.py.LOCAL.29640.py
./GPy/likelihoods/link_functions.py.BACKUP.29640.py
./GPy/likelihoods/link_functions.py.REMOTE.29640.py
./GPy/core/fitc.py.BASE.31878.py
./GPy/core/fitc.py.LOCAL.31878.py
./GPy/core/fitc.py.REMOTE.31878.py
./GPy/core/fitc.py.BACKUP.31878.py

Please remove them

**Comment by nfusi** [comment] 2015-04-19 17:11
duplicate of #169

**Comment by mzwiessele** [comment] 2015-09-09 17:57
Fixed

**Closed by mzwiessele** 2015-09-09 17:57 UTC
Labels: duplicate
